version: '3.8'

services:
  backend-api-sp-auth:
    container_name: backend-api-sp-auth
    image: node:lts-stretch
    restart: unless-stopped
    ports:
      - 8082:8080
    volumes: # https://docs.docker.com/docker-for-mac/osxfs-caching/
      - ./back/:/usr/app:delegated
      - ./:/all-projects:delegated
    networks:
      - backend
    depends_on:
      - redis-sp-auth
      - backend-database-sp-auth
    environment:
      PORT: 8080
      # ADMIN_API_KEY: $ADMIN_API_KEY
      # GOOGLE_PROJECT_ID: "mrh-morgan-free-scrap"
      # GOOGLE_PROJECT_LOCATION: "europe-west1"
      AUTH_REDIS_URL: redis://redis-sp-auth:6379/0
      DB_CACHE_REDIS_URL: redis://:redis@redis-sp-auth:6379/0
      DB_HOST: 'backend-database-sp-auth'
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: pass
      DB_DATABASE: postgres
      ACCESS_TOKEN_SECRET: lkddsijdief56kdsjsd5ds5csdcdjcjkdlskjGHJEOKDLLKZMMSd6sfd5s4cd4cskdckdsnjfcdssk6966
      REFRESH_TOKEN_SECRET: r3p67zIY4TlYzTvu1VC6r3mV54545x1j
      ACCESS_TOKEN_LIFE: 120
      REFRESH_TOKEN_LIFE: 600
    working_dir: /usr/app
    command: yarn dev

  e2e-test-backend-api-sp-auth:
    container_name: e2e-test-backend-api-sp-auth
    image: node:lts-stretch
    restart: unless-stopped
    ports:
      - 8182:8080
    volumes: # https://docs.docker.com/docker-for-mac/osxfs-caching/
      - ./back/:/usr/app:delegated
      - ./:/all-projects:delegated
    networks:
      - backend
    depends_on:
      - e2e-test-redis-sp-auth
      - e2e-test-backend-database-sp-auth
    environment:
      PORT: 8080
      # ADMIN_API_KEY: $ADMIN_API_KEY
      # GOOGLE_PROJECT_ID: "mrh-morgan-free-scrap"
      # GOOGLE_PROJECT_LOCATION: "europe-west1"
      AUTH_REDIS_URL: redis://e2e-test-redis-sp-auth:6379/0
      DB_CACHE_REDIS_URL: redis://:redis@e2e-test-redis-sp-auth:6379/0
      DB_HOST: 'e2e-test-backend-database-sp-auth'
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: pass
      DB_DATABASE: postgres
      ACCESS_TOKEN_SECRET: lkddsijdief56kdsjsd5ds5csdcdjcjkdlskjGHJEOKDLLKZMMSd6sfd5s4cd4cskdckdsnjfcdssk6966
      REFRESH_TOKEN_SECRET: r3p67zIY4TlYzTvu1VC6r3mV54545x1j
      ACCESS_TOKEN_LIFE: 120
      REFRESH_TOKEN_LIFE: 600
    working_dir: /usr/app
    command: yarn dev

  backend-database-sp-auth:
    container_name: backend-database-sp-auth
    image: postgres:13.4
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/db-files/

  e2e-test-backend-database-sp-auth:
    container_name: e2e-test-backend-database-sp-auth
    image: postgres:13.4
    restart: always
    volumes:
      - e2e-test-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/db-files/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend
    environment:
      ADMINER_DEFAULT_SERVER: backend-database-mrh

  redis-sp-auth:
    container_name: redis-sp-auth
    image: 'redis:5-alpine'
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 9003:6379
    networks:
      - backend
    volumes:
      - redis_data:/data

  e2e-test-redis-sp-auth:
    container_name: e2e-test-redis-sp-auth
    image: 'redis:5-alpine'
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 9004:6379
    networks:
      - backend
    volumes:
      - ./e2e/tmpredisdata:/data

networks:
  backend:

volumes:
  db-data:
  e2e-test-db-data:
  redis_data:
