version: '3.8'

services:
  backend-api-sp-auth:
    container_name: backend-api-sp-auth
    image: node:lts-stretch
    restart: unless-stopped
    ports:
      - 8082:8080
    volumes: # https://docs.docker.com/docker-for-mac/osxfs-caching/
      - ./back/:/usr/app:delegated
      - ./:/all-projects:delegated
    networks:
      - backend
    depends_on:
      - redis-sp-auth
    environment:
      PORT: 8080
      # ADMIN_API_KEY: $ADMIN_API_KEY
      # GOOGLE_PROJECT_ID: "mrh-morgan-free-scrap"
      # GOOGLE_PROJECT_LOCATION: "europe-west1"
      FIRESTORE_EMULATOR_HOST: firebase-tools:8080
      AUTH_REDIS_URL: redis://redis-sp-auth:6379/0
    working_dir: /usr/app
    command: yarn dev

  e2e-test-backend-api-sp-auth:
    container_name: e2e-test-backend-api-sp-auth
    image: node:lts-stretch
    restart: unless-stopped
    ports:
      - 8182:8080
    volumes: # https://docs.docker.com/docker-for-mac/osxfs-caching/
      - ./back/:/usr/app:delegated
      - ./:/all-projects:delegated
    networks:
      - backend
    depends_on:
      - e2e-test-redis-sp-auth
    environment:
      PORT: 8080
      # ADMIN_API_KEY: $ADMIN_API_KEY
      # GOOGLE_PROJECT_ID: "mrh-morgan-free-scrap"
      # GOOGLE_PROJECT_LOCATION: "europe-west1"
      FIRESTORE_EMULATOR_HOST: e2e-test-firebase-tools:8180
      AUTH_REDIS_URL: redis://e2e-test-redis-sp-auth:6379/0
    working_dir: /usr/app
    command: yarn dev

  firebase-tools-sp-auth:
    container_name: firebase-tools-sp-auth
    image: andreysenov/firebase-tools
    restart: unless-stopped
    ports:
      - 9099:9099
      - 9005:9005
      - 9000:9000
      - 8085:8085
      - 8080:8080
      - 5001:5001
      - 5000:5000
      - 4000:4000
    volumes:
      - db-data:/home/node
    networks:
      - backend
    working_dir: /home/node
    command: firebase emulators:start

  e2e-test-firebase-tools-sp-auth:
    container_name: e2e-test-firebase-tools-sp-auth
    image: andreysenov/firebase-tools
    restart: unless-stopped
    ports:
      - 9199:9099
      - 9105:9005
      - 9100:9000
      - 8185:8085
      - 8180:8080
      - 5101:5001
      - 5100:5000
      - 4100:4000
    volumes:
      - ./e2e/tmpdbdata:/home/node
    networks:
      - backend
    working_dir: /home/node
    command: firebase emulators:start

  redis-sp-auth:
    container_name: redis-sp-auth
    image: 'redis:5-alpine'
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 9003:6379
    networks:
      - backend
    volumes:
      - redis_data:/data

  e2e-test-redis-sp-auth:
    container_name: e2e-test-redis-sp-auth
    image: 'redis:5-alpine'
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 9004:6379
    networks:
      - backend
    volumes:
      - ./e2e/tmpredisdata:/data

networks:
  backend:
    driver: bridge

volumes:
  db-data:
  e2e-test-db-data:
  redis_data:
