services:
  - docker:dind

include:
  - template: SAST.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/Dependency-Scanning.gitlab-ci.yml

.default_rule: &default_rule
  if: '$CI_COMMIT_BRANCH =~ /^feature|^fix|^hotfix|^bugfix|^release|^snyk-fix/'

stages:
  - test
  - prepare
  - check
  - check
  - deploy

install_back_dependencies:
  stage: prepare
  image: node:lts
  script:
    - cd back
    - yarn install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - back/node_modules/
  rules:
    - *default_rule
    - if: '$CI_COMMIT_BRANCH == "develop"' # setting fixed value `develop` -- could be set to a var: $CI_DEFAULT_BRANCH
    - if: '$CI_COMMIT_TAG =~ /^v.+/'

check:test:
  stage: check
  image: node:lts
  services:
    - name: redis:5.0-alpine
      alias: e2e-test-redis
  script:
    - yarn test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - node_modules/
  rules:
    - *default_rule
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_TAG =~ /^v.+/'

check:lint:
  stage: check
  image: node:lts
  script:
    - yarn run lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - node_modules/
  rules:
    - *default_rule
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_TAG =~ /^v.+/'
